{% set name = "sacred" %}
{% set version = "0.8.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sacred-{{ version }}.tar.gz
  sha256: c2a01d9b524c1d16076cb40c21071dc049bf68fe5f02a2cac78bbb3169e407d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - docopt >=0.3,<1.0
    - jsonpickle >=2.2
    - munch >=2.5,<5.0
    - wrapt >=1.0,<2.0
    - py-cpuinfo >=4.0
    - colorama >=0.4
    - packaging >=18.0
    - gitpython
test:
  imports:
    - sacred
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/IDSIA/sacred
  summary: Facilitates automated and reproducible experimental research
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - n-gao
    - siboehm
